In [50]:
import pandas as pd
import numpy as np
import psycopg2

In [51]:
# 读取winemag-data_first150k.csv文件，且索引为其第一列
BaileyAve = pd.read_csv('BaileyAve.csv')
DelawareAve = pd.read_csv('DelawareAve.csv')
ElmwoodAve = pd.read_csv('ElmwoodAve.csv')
FillmoreAve = pd.read_csv('FillmoreAve.csv')
HertelAve = pd.read_csv('HertelAve.csv')
JeffersonAve = pd.read_csv('JeffersonAve.csv')
MainSt = pd.read_csv('MainSt.csv')
NiagaraSt = pd.read_csv('NiagaraSt.csv')
# 保存animals数据集为文件cows_and_goats.csv
#animals.to_csv("cows_and_goats.csv")

In [52]:
BaileyAvePT = BaileyAve.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
DelawareAve = DelawareAve.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
ElmwoodAve = ElmwoodAve.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
FillmoreAve = FillmoreAve.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
HertelAve = HertelAve.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
JeffersonAve = JeffersonAve.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
MainSt = MainSt.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)
NiagaraSt = NiagaraSt.pivot_table(index=['Intersection_ID','starttime'], columns=['startdate'], values=['ped'], aggfunc=np.sum)

In [53]:
BaileyAvePT.to_csv('BaileyAvePT1.csv')
DelawareAve.to_csv('DelawareAve1.csv')
ElmwoodAve.to_csv('ElmwoodAve1.csv')
FillmoreAve.to_csv('FillmoreAve1.csv')
HertelAve.to_csv('HertelAve1.csv')
JeffersonAve.to_csv('JeffersonAve1.csv')
MainSt.to_csv('MainSt1.csv')
NiagaraSt.to_csv('NiagaraSt1.csv')

In [54]:
BaileyAvePT.sort_index(axis=1)

                                ped                                            \
startdate                 1/14/2020 10/4/2017 11/10/2009 11/20/2007 6/10/2015
Intersection_ID starttime
192             12:00:00        1.0       NaN        NaN        NaN       NaN
                12:15:00        1.0       NaN        NaN        NaN       NaN
                12:30:00        2.0       NaN        NaN        NaN       NaN
                12:45:00        0.0       NaN        NaN        NaN       NaN
                13:00:00        3.0       NaN        NaN        NaN       NaN
...                             ...       ...        ...        ...       ...
1927            8:45:00         NaN       NaN        NaN        NaN       NaN
                9:00:00         NaN       NaN        NaN        NaN       NaN
                9:15:00         NaN       NaN        NaN        NaN       NaN
                9:30:00         NaN       NaN        NaN        NaN       NaN
                9:45:00         NaN       NaN        NaN        NaN       NaN

                                                                             \
startdate                 6/12/2006 6/13/2006 6/14/2006 6/15/2006 6/15/2010
Intersection_ID starttime
192             12:00:00        NaN       NaN       NaN       NaN       NaN
                12:15:00        NaN       NaN       NaN       NaN       NaN
                12:30:00        NaN       NaN       NaN       NaN       NaN
                12:45:00        NaN       NaN       NaN       NaN       NaN
                13:00:00        NaN       NaN       NaN       NaN       NaN
...                             ...       ...       ...       ...       ...
1927            8:45:00         NaN       NaN       NaN       NaN       NaN
                9:00:00         NaN       NaN       NaN       NaN       NaN
                9:15:00         NaN       NaN       NaN       NaN       NaN
                9:30:00         NaN       NaN       NaN       NaN       NaN
                9:45:00         NaN       NaN       NaN       NaN       NaN

                           ...                                         \
startdate                  ... 8/27/2019 8/29/2013 8/3/2015 8/30/2011
Intersection_ID starttime  ...
192             12:00:00   ...       NaN       NaN      NaN       4.0
                12:15:00   ...       NaN       NaN      NaN       2.0
                12:30:00   ...       NaN       NaN      NaN       0.0
                12:45:00   ...       NaN       NaN      NaN       4.0
                13:00:00   ...       NaN       NaN      NaN       9.0
...                        ...       ...       ...      ...       ...
1927            8:45:00    ...       NaN       NaN      NaN       NaN
                9:00:00    ...       NaN       NaN      NaN       NaN
                9:15:00    ...       NaN       NaN      NaN       NaN
                9:30:00    ...       NaN       NaN      NaN       NaN
                9:45:00    ...       NaN       NaN      NaN       NaN

                                                                         \
startdate                 8/30/2017 8/4/2015 8/5/2015 8/6/2015 8/9/2012
Intersection_ID starttime
192             12:00:00        NaN      NaN      NaN      NaN      3.0
                12:15:00        NaN      NaN      NaN      NaN      3.0
                12:30:00        NaN      NaN      NaN      NaN      3.0
                12:45:00        NaN      NaN      NaN      NaN      2.0
                13:00:00        NaN      NaN      NaN      NaN      1.0
...                             ...      ...      ...      ...      ...
1927            8:45:00         NaN      NaN      NaN      NaN      NaN
                9:00:00         NaN      NaN      NaN      NaN      NaN
                9:15:00         NaN      NaN      NaN      NaN      NaN
                9:30:00         NaN      NaN      NaN      NaN      NaN
                9:45:00         NaN      NaN      NaN      NaN      NaN


startdate                 9/10/2019
Intersection_ID starttime
192             12:00:00        NaN
                12:15:00        NaN
                12:30:00        NaN
                12:45:00        NaN
                13:00:00        NaN
...                             ...
1927            8:45:00         NaN
                9:00:00         NaN
                9:15:00         NaN
                9:30:00         NaN
                9:45:00         NaN

[992 rows x 37 columns]

In [55]:
con = psycopg2.connect(database='URP511_FINAL_DPROC', user='postgres',
        password='707096')